type RoleMap = {
  SUPER_ADMIN: string;
  ADMIN: string;
  MANAGER: string;
  MEMBER: string;
  USER: string;
};

export const ROLES: RoleMap = {
  SUPER_ADMIN: 'SUPER_ADMIN',
  ADMIN: 'ADMIN',
  MANAGER: 'MANAGER',
  MEMBER: 'MEMBER',
  USER: 'USER',
};

export const USER_STATUS = {
  ACTIVE: 'ACTIVE',
  PENDING_APPROVAL: 'PENDING_APPROVAL',
};

export const SUBSCRIPTION_TIERS = {
  FREE: 'FREE',
  PRO: 'PRO',
  BUSINESS: 'BUSINESS',
  ENTERPRISE: 'ENTERPRISE',
};

export const SUBSCRIPTION_STATUS = {
  ACTIVE: 'ACTIVE',
  PAST_DUE: 'PAST_DUE',
  CANCELED: 'CANCELED',
  INCOMPLETE: 'INCOMPLETE',
};

export const TASK_STATUS = {
  BACKLOG: 'BACKLOG',
  TODO: 'TODO',
  IN_PROGRESS: 'IN_PROGRESS',
  IN_REVIEW: 'IN_REVIEW',
  DONE: 'DONE',
  ARCHIVED: 'ARCHIVED',
};

export const TASK_PRIORITY = {
  LOW: 'LOW',
  MEDIUM: 'MEDIUM',
  HIGH: 'HIGH',
  URGENT: 'URGENT',
};

export const ACTIVITY_ACTIONS = {
  CREATE: 'CREATE',
  UPDATE: 'UPDATE',
  DELETE: 'DELETE',
  ASSIGN: 'ASSIGN',
  UNASSIGN: 'UNASSIGN',
  COMMENT: 'COMMENT',
  STATUS_CHANGE: 'STATUS_CHANGE',
  // Auth
  LOGIN_SUCCESS: 'LOGIN_SUCCESS',
  LOGIN_FAILURE: 'LOGIN_FAILURE',
  REGISTER_SUCCESS: 'REGISTER_SUCCESS',
  REGISTER_FAILURE: 'REGISTER_FAILURE',
  OTP_VERIFIED: 'OTP_VERIFIED',
  LOGOUT: 'LOGOUT',
  // Admin
  USER_APPROVED: 'USER_APPROVED',
  USER_SUSPENDED: 'USER_SUSPENDED',
  BULK_ACTION: 'BULK_ACTION',
  // System
  SERVER_START: 'SERVER_START',
  DB_CONNECTED: 'DB_CONNECTED',
  API_ERROR: 'API_ERROR',
  API_REQUEST: 'API_REQUEST',
};

export const NOTIFICATION_TYPES = {
  TASK_ASSIGNED: 'TASK_ASSIGNED',
  TASK_UPDATED: 'TASK_UPDATED',
  COMMENT_ADDED: 'COMMENT_ADDED',
  MENTION: 'MENTION',
  PROJECT_INVITE: 'PROJECT_INVITE',
};

export const PERMISSIONS = {
  CREATE_TASK: 'CREATE_TASK',
  DELETE_TASK: 'DELETE_TASK',
  INVITE_USER: 'INVITE_USER',
  VIEW_PROJECT: 'VIEW_PROJECT',
  MANAGE_WORKSPACE: 'MANAGE_WORKSPACE',
  // Add more as needed
};
