export const ROLES = {
  SUPER_ADMIN: 'SUPER_ADMIN',
  ADMIN: 'ADMIN',
  USER: 'USER',
};

export const USER_STATUS = {
  ACTIVE: 'ACTIVE',
  PENDING_APPROVAL: 'PENDING_APPROVAL',
};

export const SUBSCRIPTION_TIERS = {
  FREE: 'FREE',
  PRO: 'PRO',
  BUSINESS: 'BUSINESS',
  ENTERPRISE: 'ENTERPRISE',
};

export const SUBSCRIPTION_STATUS = {
  ACTIVE: 'ACTIVE',
  PAST_DUE: 'PAST_DUE',
  CANCELED: 'CANCELED',
  INCOMPLETE: 'INCOMPLETE',
};

export const TASK_STATUS = {
  BACKLOG: 'BACKLOG',
  TODO: 'TODO',
  IN_PROGRESS: 'IN_PROGRESS',
  IN_REVIEW: 'IN_REVIEW',
  DONE: 'DONE',
  ARCHIVED: 'ARCHIVED',
};

export const TASK_PRIORITY = {
  LOW: 'LOW',
  MEDIUM: 'MEDIUM',
  HIGH: 'HIGH',
  URGENT: 'URGENT',
};

export const ACTIVITY_ACTIONS = {
  CREATE: 'CREATE',
  UPDATE: 'UPDATE',
  DELETE: 'DELETE',
  ASSIGN: 'ASSIGN',
  UNASSIGN: 'UNASSIGN',
  COMMENT: 'COMMENT',
  STATUS_CHANGE: 'STATUS_CHANGE',
};

export const NOTIFICATION_TYPES = {
  TASK_ASSIGNED: 'TASK_ASSIGNED',
  TASK_UPDATED: 'TASK_UPDATED',
  COMMENT_ADDED: 'COMMENT_ADDED',
  MENTION: 'MENTION',
  PROJECT_INVITE: 'PROJECT_INVITE',
};

export const PERMISSIONS = {
  CREATE_TASK: 'CREATE_TASK',
  DELETE_TASK: 'DELETE_TASK',
  INVITE_USER: 'INVITE_USER',
  VIEW_PROJECT: 'VIEW_PROJECT',
  MANAGE_WORKSPACE: 'MANAGE_WORKSPACE',
  // Add more as needed
};
