/**
 * Frontend permissions constants
 * Must match backend PERMISSIONS from src/constants/index.ts
 */

export const PERMISSIONS = {
  // Project Management
  CREATE_PROJECT: 'CREATE_PROJECT',
  VIEW_PROJECT: 'VIEW_PROJECT',
  EDIT_PROJECT: 'EDIT_PROJECT',
  DELETE_PROJECT: 'DELETE_PROJECT',
  
  // Task Management
  CREATE_TASK: 'CREATE_TASK',
  VIEW_TASK: 'VIEW_TASK',
  EDIT_TASK: 'EDIT_TASK',
  DELETE_TASK: 'DELETE_TASK',
  MOVE_TASK: 'MOVE_TASK',
  
  // Comment & Collaboration
  CREATE_COMMENT: 'CREATE_COMMENT',
  EDIT_COMMENT: 'EDIT_COMMENT',
  DELETE_COMMENT: 'DELETE_COMMENT',
  
  // Member & Organization Management
  INVITE_USER: 'INVITE_USER',
  MANAGE_MEMBERS: 'MANAGE_MEMBERS',
  REMOVE_MEMBER: 'REMOVE_MEMBER',
  CHANGE_MEMBER_ROLE: 'CHANGE_MEMBER_ROLE',
  
  // Page & View Management
  CREATE_PAGE: 'CREATE_PAGE',
  VIEW_PAGE: 'VIEW_PAGE',
  EDIT_PAGE: 'EDIT_PAGE',
  DELETE_PAGE: 'DELETE_PAGE',
  VIEW_PRIVATE_PAGE: 'VIEW_PRIVATE_PAGE',
  
  // Workspace & Settings
  MANAGE_WORKSPACE: 'MANAGE_WORKSPACE',
  MANAGE_SETTINGS: 'MANAGE_SETTINGS',
  VIEW_ANALYTICS: 'VIEW_ANALYTICS',
  MANAGE_BILLING: 'MANAGE_BILLING',
} as const;
